# Generated by Django 2.0.5 on 2018-06-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beer_ID', models.IntegerField()),
                ('Beer_Name', models.CharField(max_length=255)),
                ('Beer_Brewery', models.CharField(max_length=255)),
                ('Beer_Type', models.CharField(max_length=150)),
                ('Beer_Percent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Beer_Rating', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brewery_ID', models.IntegerField()),
                ('Brewery_Name', models.CharField(max_length=255)),
                ('Brewery_Town', models.CharField(max_length=255)),
                ('Brewery_Region', models.CharField(max_length=150)),
                ('Brewery_Latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Brewery_Longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Brewery_URL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brewery_ID', models.IntegerField()),
                ('Type_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Types_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Name', models.IntegerField()),
            ],
        ),
    ]
