# Generated by Django 2.0.5 on 2018-07-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beer_Name', models.CharField(max_length=155)),
                ('Beer_Brewery', models.CharField(max_length=155)),
                ('Beer_Type', models.CharField(max_length=90)),
                ('Beer_Percent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Beer_Rating', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brewery_Name', models.CharField(max_length=90)),
                ('Brewery_Region', models.CharField(default='Dublin', max_length=90)),
                ('Brewery_Address', models.CharField(default='Dublin, Ireland', max_length=500)),
                ('Brewery_Type', models.CharField(default='Brewery', max_length=50)),
                ('Brewer_Rating', models.DecimalField(decimal_places=2, default=2.5, max_digits=2)),
                ('Brewery_Latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Brewery_Longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Brewery_URL', models.URLField(blank=True, max_length=255, null=True)),
                ('Brewery_Twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('Brewery_Facebook', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
