# Generated by Django 2.0.5 on 2018-06-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theCraftMapsCO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer_table',
            name='Beer_ID',
        ),
        migrations.RemoveField(
            model_name='brewery_table',
            name='Brewery_ID',
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewery_Latitude',
            field=models.DecimalField(decimal_places=30, max_digits=50),
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewery_Longitude',
            field=models.DecimalField(decimal_places=30, max_digits=50),
        ),
    ]
