# Generated by Django 2.0.5 on 2018-07-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theCraftMapsCO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer_table',
            name='Beer_Percent',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='beer_table',
            name='Beer_Rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewer_Rating',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=2),
        ),
    ]
