# Generated by Django 2.0.5 on 2018-06-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theCraftMapsCO', '0002_auto_20180618_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brewery_Types',
        ),
        migrations.DeleteModel(
            name='Types_Table',
        ),
        migrations.AddField(
            model_name='brewery_table',
            name='Brewery_Type',
            field=models.CharField(default='Brewery', max_length=150),
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewery_Latitude',
            field=models.DecimalField(decimal_places=10, max_digits=50),
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewery_Longitude',
            field=models.DecimalField(decimal_places=10, max_digits=50),
        ),
    ]
