# Generated by Django 2.0.5 on 2018-07-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theCraftMapsCO', '0003_auto_20180622_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery_table',
            name='Brewery_Town',
        ),
        migrations.AddField(
            model_name='brewery_table',
            name='Brewer_Rating',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='brewery_table',
            name='Brewery_Address',
            field=models.CharField(default='Dublin, Ireland', max_length=500),
        ),
        migrations.AddField(
            model_name='brewery_table',
            name='Brewery_Facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brewery_table',
            name='Brewery_Twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beer_table',
            name='Beer_Brewery',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='beer_table',
            name='Beer_Name',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='beer_table',
            name='Beer_Type',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewery_Latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewery_Longitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewery_Name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewery_Region',
            field=models.CharField(default='Dublin', max_length=90),
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewery_Type',
            field=models.CharField(default='Brewery', max_length=50),
        ),
        migrations.AlterField(
            model_name='brewery_table',
            name='Brewery_URL',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
